### PR TITLE
Add Chinese translation for callbacklist reference

### PR DESCRIPTION
**Pull request by marsCatXdu**
Signed-off-by: marsCatXDU <marscatcn@live.com>

### CODE REVIEW

**Comment by wqking** [comment]
Thanks. I labeled the PR as WIP, because I think you will add more translations?
I will leave this PR there so you can continue on it. Just add any new commits to the same branch in the PR, then the commits will appear and be included in the PR.
Don't hesitate to let me know when you finish it or you think it's any milestone, then I can merge it.

**Comment by wqking** [comment]
BTW, some documents have special tags such like `<a id="a2_5"></a>`, which are used for the TOC that's generated by a Perl script I'm going to abandon. So in the Chinese documents, if you have better way to generate the TOC, such as the markdown plugin in Visual Studio Code, then feel free to remove the tags and re-generate the TOC in your way. Though it's fine to leave the tags and the old TOC there.

**Comment by marsCatXdu** [comment]
> Thanks. I labeled the PR as WIP, because I think you will add more translations? I will leave this PR there so you can continue on it. Just add any new commits to the same branch in the PR, then the commits will appear and be included in the PR. Don't hesitate to let me know when you finish it or you think it's any milestone, then I can merge it.

Ok. The next milestone is to finish "Core classes and functions" part

**Comment by wqking** [comment]
I merge this PR to allow others use the Chinese translation for callback list.  
For future translations, feel free to create new PRs.

**Pull request merged**
