### PR TITLE
Cmake support

### PR DESCRIPTION
**Pull request by rotolof**
I wanted to integrate the library in my CMake project so I wrote this. It should allow one to either:

- Install the library in the system with:
  
  ```sh
  mkdir build && cd build
  cmake ..
  sudo make install
  ```
  
  Then use it in CMake:
  
  ```cmake
  find_package(eventpp)
  target_link_libraries(mytarget eventpp::eventpp)
  ```

- Or import it with `FetchContent`:
  
  ```cmake 
  include(FetchContent)
  FetchContent_Declare(
    eventpp
    GIT_REPOSITORY https://github.com/wqking/eventpp.git
    GIT_TAG master
  )
  FetchContent_MakeAvailable(eventpp)
  
  target_link_libraries(mytarget eventpp::eventpp)
  ```

### CODE REVIEW

**Comment by wqking** [comment]
This is great feature, thanks for the contribute.
 I will check and see if I can add some integration tests for it.

**Comment by rotolof** [comment]
You are welcome! I think you can easily integrate your `tests` directory with something like:
```cmake
include(CTest)
if(BUILD_TESTING)
  add_subdirectory(tests)
endif()
```

**Comment by wqking** [comment]
I merged the code to master, with some code style change and updated readme.
According to my test, it works very well on Linux (I tested on Ubuntu 16.04), but on Win10 with MingW, it fails to include the proper eventpp path in the project using `target_link_libraries(mytest eventpp::eventpp)`.
I don't know why, though it's not a big problem. Maybe because I used CMAKE_INSTALL_PREFIX to specify the library folder.

**Comment by rotolof** [comment]
Unfortunately I have zero experience with CMake on Windows, probably it has something to do with the fact that I used the [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) module.

**Pull request merged**
