### PR TITLE
Ci working for ubuntu-latest & windows-latest. 

### PR DESCRIPTION
**Pull request by OlivierLDff**
* Tests are working on `ubuntu-latest` & `windows-latest`.
* Tests are failing (building) on `macOs-latest`. I will push later the update ci file when code will be fixed for macos.
* I'm using `ctest` to trigger all test in cross platform way. To enable ctest i added `enable_testing()` in main `CMakelists.txt` and i registered the 2 tests with `add_test()`.
* ci will is triggered on every push & pull request

### CODE REVIEW

**Comment by wqking** [comment]
Great. I will merge the PR afte you fix the MacOS issue. Or if you want to merge now, let me know.

**Comment by OlivierLDff** [comment]
You should merge this PR now, i will look at the mac issue when i will have time. But it's not a critical issue for me, so i will look at it when i will have free time.

**Comment by OlivierLDff** [comment]
You can also display the badge in the readme now CI
or even better
[CI](https://github.com/wqking/eventpp/actions)

**Comment by wqking** [comment]
Added the badget. Thanks :)

**Comment by bmahlbrand** [comment]
> I fixed the build errors on MacOS, and added macos to the CI.
> @bmahlbrand I would appreciate if you can test the `master` branch to see if it compiles on your MacOS.

I can confirm this is working in my pipeline for macos as well now. Thanks to you both for the quick turnaround! I'm in the same boat, where I don't have a Mac to test on.

**Pull request merged**
