### PR TITLE
Added auto get / set prefixes

### PR DESCRIPTION
**Pull request by Drise13**
Added automatic get/set prefixes. Reduced required arg count to 2. Changed variable prefix to more common underscore.

I am not sure with the current architecture how to support backwards compatible 3 arg code.

I changed `v` prefix to `_` so expanded documentation is easier to read.
I added an overridable get/set prefix as macros that can be re-defined as needed.

### CODE REVIEW

**Comment by Drise13** [comment]
Thinking about it more, it might be better to have this as a separate AUTO_GET_SET macro or something, if you want to preserve backwards compatibility. It would also allow for the use of `get` only based macros. Just a thought.

**Comment by wqking** [comment]
Good job, thanks for the PR.

Some thoughts,
1, Back compatibility is important. We should not break back compatibility unless we have to.
2, It's not common use case to add setter for a data field in an Event object, most Event objects are read only.
3, Getter prefix doesn't need to be "get", it can also be "is", "can", "should", etc.

So, we can't modify EVENTPP_MAKE_EVENT as you did in this PR. It's not bad idea to support auto getter/setter, but in other ways.
One way is add another macro such as EVENTPP_MAKE_EVENT_AUTO_GETTER_SETTER in parallel of EVENTPP_MAKE_EVENT. This is not very good because it not only introduces duplicated code but also all fields in EVENTPP_MAKE_EVENT_AUTO_GETTER_SETTER will contain setters, which is not necessary in most cases.
Another way I recommend is, we can introduce a new utility macro, such as EVENTPP_AUTO_GETTER_SETTER, and it expands, for example, `(int, Value)`, to `(int, getValue, setValue)` and passes the result to EVENTPP_MAKE_EVENT.
For example, pseudo code,
```
EVENTPP_MAKE_EVENT(
    EventDraw, Event, EventType::draw,
    (std::string, getText, setText), EVENTPP_AUTO_GETTER_SETTER(int, X), (double, getSize)
);
```
Then there are `getX()` and `setX()` in the expanded code.

It sees `EVENTPP_AUTO_GETTER_SETTER` is pretty long and verbose to write, but the best benefits beside back compatibility are, it gives the most freedom to the users, and it gives the uniform format for auto getter/setter, and it satisfies `eventpp` philosophy very well : "the core is small, functions are added by utilities".
And if the user feels verbose, he can always define shortcuts, for example,
```
#define GS EVENTPP_AUTO_GETTER_SETTER

EVENTPP_MAKE_EVENT(
    EventDraw, Event, EventType::draw,
    (std::string, getText, setText), GS(int, X), (double, getSize)
);

#undefine GS
```

Let me know your opinion.

**Comment by Drise13** [comment]
I agree with everything you mentioned and think its a much better general approach. Would you prefer to take over the PR from here? I think that's probably best.

**Comment by wqking** [comment]
I may take it over but it's low priority to me for now. You may also close this PR and implement it in another new PR, if you like.

**Comment by wqking** [comment]
I will add it as a tip in the document, rather than part of the library.

**Comment by wqking** [comment]
I've added the tip.

**Pull request closed without merging**
